apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/etsauer-acme/demo-gitops
    targetRevision: HEAD
    path: auth
    helm:
      releaseName: auth
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-config
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
