repoURL: https://github.com/etsauer-acme/demo-gitops
targetRevision: HEAD

applications:
  - name: auth
    namespace: auth
    values:
      github:
        oauthOpenShiftId: 30662b469ae21c96c98b
        teams:
          - etsauer-acme/aap-on-ocp
  - name: rbac
    namespace: rbac
